### NumPy

+ Numpyは数値計算を効率的に行うためのPython拡張ライブラリ
+ 多次元配列の操作/演算を行うのに便利
+ 機械学習では必須のライブラリです
+ 全ての操作を覚える必要はありません
+ 基本的な操作のみ覚えて必要に応じて公式ドキュメントを利用

In [1]:
import numpy as np

In [2]:
np.version.full_version

'1.19.4'

#### 配列

+ ```np.array()```Numpy配列の生成
+ ```type（）```numpy.ndarray(n次元のdimension)
+ ```.shape```(row,col)各次元の配列のサイズを確認
 > + ```.shape[0]```(row)
 > + ```.shape[1]```(col)
+ ```.dtype```要素のデータ型確認/指定
+ ```.astype()```型変換
+ ```array[0]```で0行目の要素のアクセス
+ ```array[2,3」```で2行目3列目の要素のアクセス
+ ```array[:2]```で2行までアクセス
+ ```array[2:]```で行2からアクセス
+ ```array[:2, 1]```行2までの列1へアクセス
+ ```np.zeros()``` 要素が全て0のNumpy配列の生成
+ ```np.ones()``` 要素が全て1のNumpy配列の生成
+ ```np.full()``` 指定した値を持つNumpy配列の生成
+ ```np.eye()``` 単位行列のNumpy配列を生成

In [3]:
a = np.array([1, 2, 3])

In [4]:
type(a)    # n dimension：n次元

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.dtype

dtype('int64')

In [7]:
a[0]

1

In [9]:
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b.shape    # 2行３列

(2, 3)

In [11]:
b[0]

array([1, 2, 3])

In [12]:
b[0][0]    # bの0行0列

1

In [13]:
b[0, 0]    # bの0行0列

1

In [14]:
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8],  [9, 10, 11, 12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
c.shape

(3, 4)

In [16]:
c[:2]    #2行目以前をアクセス

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
np.zeros((3, 3))    # 要素が全て0のNumpy配列の生成

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((2, 2))    # 要素が全て1のNumpy配列の生成

array([[1., 1.],
       [1., 1.]])

In [19]:
np.full((3, 5), 10)   #指定した値（１０）の3行５列生成

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [20]:
np.eye(10)    # i 単位行列生成(identity matrix)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### 基本演算

+ array + arrayは各要素の足し算
+ array - arrayは各要素の引き算
+ array * arrayは各要素の掛け算
+ array ** 2は各要素の自乗
+ array / 2は各要素の2の割り算
+ array < 2は各要素が2より小さいかどうかのboolean
+ PythonリストとNumpy配列の処理の違い

In [21]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [22]:
a + b    # 各要素ごとに演算処理が行われる

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [23]:
a - b

array([[0, 0, 0],
       [0, 0, 0]])

In [24]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [26]:
a / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [27]:
a % 2

array([[1, 0, 1],
       [0, 1, 0]])

In [28]:
a < 2

array([[ True, False, False],
       [False, False, False]])

In [29]:
# Python list
py_list = [1, 2, 3]

# Numpy list
np_array = np.array([1, 2, 3])


In [31]:
np_array + [4]    # 各要素に値を演算処理

array([5, 6, 7])

In [30]:
py_list + [4]    # listの最後尾に値を挿入

[1, 2, 3, 4]

In [32]:
# Numpyと同様の処理をする場合forループさせる
list2 = []
for i in py_list:
    list2.append(i+4)
list2

[5, 6, 7]

In [33]:
py_list * 2

[1, 2, 3, 1, 2, 3]

In [34]:
np_array * 2

array([2, 4, 6])

#### 行列積 (線形代数)

+ ndarray * ndarray は各要素の掛け算
+ ```np.dot()```で行列の積を求められる
+ ```a.dot(b) = np.dot(a,b)```
+ ```np.dot(a,b)```と```np.dot(b,a)```の解は異なる場合がある
+ ```np.array(python-list)```でPythonリストをNumpy配列へ変換
+ ```np.ndarray.tolist()```でNumpy配列からPythonリストへ変換


In [35]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [36]:
a*b   # アダマール積（各要素毎の演算処理）

array([[ 5, 12],
       [21, 32]])

In [37]:
np.dot(a, b)    # 行列積

array([[19, 22],
       [43, 50]])

In [38]:
np.dot(b, a)

array([[23, 34],
       [31, 46]])

In [39]:
# Pythonリスト → Numpyリスト
c = [[1, 2], [3, 4]]     # Pythonのリスト
c = np.array(c)    # Numpyのリスト変換
c

array([[1, 2],
       [3, 4]])

In [40]:
# Numpyリスト → Pythonリスト
c = np.ndarray.tolist(c)
c

[[1, 2], [3, 4]]

#### 乱数生成

+ 乱数とはランダムな数値のこと
+ 値や分布に応じて種類が分かれている
+ 一様乱数は0〜1の一様分布(Uniform distribution)の乱数
+ 標準正規分布は標準偏差を1、平均値が0の分布の乱数
+ ```np.random.rand()``` 一様乱数の生成
+ ```np.random.randn()``` 標準正規分布の乱数生成
+ ```np.random.randint()``` 整数の乱数生成
+ ```np.random.seed()``` 乱数の種（シード）の指定
> 乱数発生の初期化: seedを固定、毎回同じ乱数生成が可能
+ ```np.random.choise()``` 

※機械学習ではデバック・テストで用いる

In [41]:
np.random.rand(10)    # 0~1の一様分布の乱数 0行１０列 生成

array([0.41434273, 0.70810873, 0.33848259, 0.85437037, 0.39985979,
       0.33372489, 0.05530662, 0.5986775 , 0.09366791, 0.08515824])

In [42]:
a = np.random.rand(10, 10)    # 0~1の一様分布の乱数 10行１０列 生成
a

array([[0.12060169, 0.08931397, 0.14253268, 0.12828903, 0.64264062,
        0.46127186, 0.72388883, 0.87336963, 0.95017363, 0.87678048],
       [0.0170546 , 0.81200979, 0.00144343, 0.18093778, 0.793046  ,
        0.72708063, 0.53572551, 0.94525469, 0.10050114, 0.96105693],
       [0.99341483, 0.89307379, 0.48198199, 0.53421177, 0.6233493 ,
        0.35997307, 0.35780818, 0.52046299, 0.64587216, 0.92674192],
       [0.3194407 , 0.61849118, 0.76632155, 0.77950074, 0.27996362,
        0.86245612, 0.79157775, 0.00372909, 0.27235402, 0.41614544],
       [0.63957427, 0.87551608, 0.51133789, 0.19049593, 0.71513922,
        0.09228334, 0.08421136, 0.44585057, 0.5702336 , 0.54546798],
       [0.04718047, 0.53755904, 0.05580088, 0.07091759, 0.5818942 ,
        0.47575427, 0.63535071, 0.37325383, 0.61253219, 0.52719106],
       [0.09689751, 0.06758076, 0.79552718, 0.92069085, 0.07976218,
        0.5604534 , 0.52953932, 0.06569066, 0.76354178, 0.19156516],
       [0.50528151, 0.6186053 , 0.8382957

In [43]:
a.shape

(10, 10)

In [44]:
# Standard Nomal Distribution(標準正規分布)
# mean(平均値)= 0 std(標準偏差)= 1 
np.random.randn(1)

array([-0.77259074])

In [45]:
randn5000 = np.random.randn(5000, 5000)    # 5000行5000列

In [46]:
randn5000.shape

(5000, 5000)

In [47]:
randn5000.mean()    # 限りなく０に近い平均値　※末尾に出たら、e-05＝１０のマイナス５乗

9.681227620984408e-05

In [48]:
randn5000.std()    # 限りなく１に近い標準偏差

0.9999494898030936

In [49]:
np.random.randint(1, 30, 30)    #1~30の乱数 0行30列 生成

array([28, 20, 13, 26, 13, 18,  8,  4,  6, 28, 25,  3, 23, 28, 21,  5, 10,
       11, 11,  4, 12,  6, 19, 11, 23, 16, 25, 11, 23, 15])

In [50]:
randint30 = np.random.randint(1, 30, (30, 30))    #1~30の乱数 30行30列 生成

In [51]:
randint30.shape

(30, 30)

In [52]:
np.random.seed(100)
np.random.randn()    # seed固定 1回目

-1.7497654730546974

In [53]:
np.random.randn()    # seed固定しない

0.34268040332750216

In [54]:
np.random.seed(100)
np.random.randn()    # seed固定　２回目（１回目同様のrandn生成）

-1.7497654730546974

#### 行列の演算と処理

+ ```np.linalg.inv(ndarray)``` ndarrayの逆行列を算出
+ ```ndarray.T``` ndarrayの転置行列(Tranposed Matrix)を算出
+ ```np.diag(ndarray)``` ndarrayの対角成分の取得

#### 内積　外積
+ ```np.inner()``` ベクトルの内積を算出
+ ```np.outer()``` ベクトルの外積を算出

Cf.[四元数と行列で見る内積と外積の「内」と「外」](https://qiita.com/7shi/items/a80988a32a0d706e9378)

In [55]:
import numpy as np
a = np.array([[2, 5], [1, 3]])
a

array([[2, 5],
       [1, 3]])

In [56]:
# a の逆行列　AA^-1 = A^-1A = I
b = np.linalg.inv(a)    # .linalg 線形代数(linear algebra) .inv 逆(inverse)
b

array([[ 3., -5.],
       [-1.,  2.]])

In [57]:
# 単位行列　I　を求めて確認
np.dot(a, b)

array([[1., 0.],
       [0., 1.]])

In [58]:
c = np.array([[3, 1], [2, 6], [4, 5]])
c

array([[3, 1],
       [2, 6],
       [4, 5]])

In [59]:
c.shape

(3, 2)

In [60]:
c.T

array([[3, 2, 4],
       [1, 6, 5]])

In [61]:
# 対角成分
d = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
d

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [62]:
# 対角線上の「１」だけ取得
np.diag(d)    # .diag : diagram

array([1, 1, 1])

In [63]:
# ベクトル
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [64]:
# ベクトル内積
np.inner(a, b)

70

In [65]:
# ベクトル外積
np.outer(a, b)

array([[ 5,  6,  7,  8],
       [10, 12, 14, 16],
       [15, 18, 21, 24],
       [20, 24, 28, 32]])

#### 数学系の関数
##### 三角関数
+ ```np.sin()``` sineを算出（度数ではなくラジアン）
+ ```np.cos()``` cosineを算出（度数ではなくラジアン）
+ ```np.tan()``` tangentを算出（度数ではなくラジアン）
+ ```np.radians()``` 度数からラジアンへ(弧度法)変換

![img](https://rikeilabo.com/wp-content/uploads/2018/11/三角比の表画像.png)

##### 指数、対数関数
+ ```np.exp()``` 指数関数（Exponential / エクスポネンシャル）
+ ```np.log()``` 対数関数（Logarithm / ロガリズム）
+ ```np.sign()``` 「正」「負」「ゼロ」を分別
+ ```np.rint()``` 小数点を四捨五入して整数にする
+ ```np.modf()``` 小数点部と整数部に分けて配列で返す

In [66]:
# tan 45° =1 
np.tan(45)    # 1 にはならない！ ∵度数ではなく、ラジアン指定の為

1.6197751905438615

In [67]:
# まず、度数からラジアンに変換
rd = np.radians(45)
rd

0.7853981633974483

In [68]:
np.tan(rd)    # ほぼ　１

0.9999999999999999

In [69]:
# sin 90° = 1
rd = np.radians(90)
np.sin(rd)

1.0

In [70]:
# 指数関数　自然対数の底「e」
np.e

2.718281828459045

In [71]:
np.exp(2)    # e^2

7.38905609893065

In [72]:
a = np.array([1, 2, 3, 4, 5])
np.exp(a)    # Exponential(指数関数)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [73]:
np.log(a)    # Logarithm(対数関数）

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [74]:
# 「-1」 「0」 「1」 で分別
b = np.array([-5, -1, -2, 0, 10, 5, -4, 3])
np.sign(b)

array([-1, -1, -1,  0,  1,  1, -1,  1])

In [75]:
c = np.random.randn(10)
c

array([ 0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,  0.51421884,
        0.22117967, -1.07004333, -0.18949583,  0.25500144, -0.45802699])

In [76]:
# 四捨五入 : round int
np.rint(c)

array([ 0.,  1., -0.,  1.,  1.,  0., -1., -0.,  0., -0.])

In [77]:
# 小数点部と整数部に分けて配列で返す
np.modf(c)

(array([ 0.3426804 ,  0.1530358 , -0.25243604,  0.98132079,  0.51421884,
         0.22117967, -0.07004333, -0.18949583,  0.25500144, -0.45802699]),
 array([ 0.,  1., -0.,  0.,  0.,  0., -1., -0.,  0., -0.]))

In [ ]:
# exam
import numpy as np
a = np.array([[2, 5, 10], [3, 6, 8], [10, 23, 1]])
a[1, 2]

In [ ]:
import numpy as np
b = np.array([[2,7,10,2],[3,43,1,9]])
b[:,2]

In [ ]:
import numpy as np
b = np.array([[2,5],[6,1]])
a = np.array([[1,3],[2,4]])

a + b

In [ ]:
import numpy as np
a = np.array([[2,3],[6,2]])
b = np.array([[1,4],[5,2]])
a * b

In [ ]:
a = np.array([[2,3],[6,2]])
b = np.array([[1,4],[5,2]])
np.dot(a, b)

In [ ]:
a = np.array([[2,1],[1,2]])
b = np.linalg.inv(a)
np.dot(a, b)