# NumPy 入門
---

+ Numpyは数値計算を効率的に行うためのPython拡張ライブラリ
+ 多次元配列の操作/演算を行うのに便利
+ 機械学習では必須のライブラリです
+ 全ての操作を覚える必要はありません
+ 基本的な操作のみ覚えて必要に応じて公式ドキュメントを利用

In [1]:
import numpy as np

In [2]:
np.version.full_version

'1.19.4'

## 配列
---

+ ```np.array()```Numpy配列の生成
+ ```type（）```numpy.ndarray(n次元のdimension)
+ ```.shape```(row,col)各次元の配列のサイズを確認
 > + ```.shape[0]```(row)
 > + ```.shape[1]```(col)
+ ```.dtype```要素のデータ型確認/指定
+ ```.astype()```型変換
+ ```array[0]```で0行目の要素のアクセス
+ ```array[2,3」```で2行目3列目の要素のアクセス
+ ```array[:2]```で2行までアクセス
+ ```array[2:]```で行2からアクセス
+ ```array[:2, 1]```行2までの列1へアクセス
+ ```np.zeros()``` 要素が全て0のNumpy配列の生成
+ ```np.ones()``` 要素が全て1のNumpy配列の生成
+ ```np.full()``` 指定した値を持つNumpy配列の生成
+ ```np.eye()``` 単位行列のNumpy配列を生成

In [3]:
a = np.array([1, 2, 3])

In [4]:
type(a)    # n dimension：n次元

numpy.ndarray

In [5]:
a.shape

(3,)

In [6]:
a.dtype

dtype('int64')

In [7]:
a[0]

1

In [8]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.shape    # 2行３列

In [10]:
b[0]

array([1, 2, 3])

In [11]:
b[0][0]    # bの0行0列

1

In [12]:
b[0, 0]    # bの0行0列

1

In [13]:
c = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
c.shape

(3, 4)

In [15]:
c[:2]    #2行目以前をアクセス

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.zeros((3, 3))    # 要素が全て0のNumpy配列の生成

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((2, 2))    # 要素が全て1のNumpy配列の生成

array([[1., 1.],
       [1., 1.]])

In [18]:
np.full((3, 5), 10)   #指定した値（１０）の3行５列生成

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [19]:
np.eye(10)    # i 単位行列生成

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## 基本演算
---

+ array + arrayは各要素の足し算
+ array - arrayは各要素の引き算
+ array * arrayは各要素の掛け算
+ array ** 2は各要素の自乗
+ array / 2は各要素の2の割り算
+ array < 2は各要素が2より小さいかどうかのboolean
+ PythonリストとNumpy配列の処理の違い

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
a + b    # 各要素ごとに演算処理が行われる

In [ ]:
a - b

In [ ]:
a * 2

In [ ]:
a ** 2

In [ ]:
a / 2

In [ ]:
a < 2

In [ ]:
# Python list
py_list = [1, 2, 3]

# Numpy list
np_array = np.array([1, 2, 3])


In [ ]:
py_list + [4]    # listの最後尾に値を挿入

In [ ]:
np_array + [4]    # 各要素に値を演算処理

In [ ]:
# Numpyと同様の処理をする場合forループさせる
list2 = []
for i in py_list:
    list2.append(i+4)
list2

In [ ]:
py_list * 2

In [ ]:
np_array * 2

## 行列積 (線形代数)
---

+ ndarray * ndarray は各要素の掛け算
+ ```np.dot()```で行列の積を求められる
+ ```a.dot(b) = np.dot(a,b)```
+ ```np.dot(a,b)```と```np.dot(b,a)```の解は異なる場合がある
+ ```np.array(python-list)```でPythonリストをNumpy配列へ変換
+ ```np.ndarray.tolist()```でNumpy配列からPythonリストへ変換


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [ ]:
a*b   # アダマール積（各要素毎の演算処理）

In [ ]:
np.dot(a, b)    # 行列積

In [ ]:
# Pythonリスト → Numpyリスト
c = [[1, 2], [3, 4]]     # Pythonのリスト
c = np.array(c)    # Numpyのリスト変換
c

In [ ]:
# Numpyリスト → Pythonリスト
c = np.ndarray.tolist(c)
c

## 乱数生成
---

+ 乱数とはランダムな数値のこと
+ 値や分布に応じて種類が分かれている
+ 一様乱数は0〜1の一様分布(Uniform distribution)の乱数
+ 標準正規分布は標準偏差を1、平均値が0の分布の乱数
+ ```np.random.rand()``` 一様乱数の生成
+ ```np.random.randn()``` 標準正規分布の乱数生成
+ ```np.random.randint()``` 整数の乱数生成
+ ```np.random.seed()``` 乱数の種（シード）の指定
> 乱数発生の初期化: seedを固定、毎回同じ乱数生成が可能
+ ```np.random.choise()``` 

※機械学習ではデバック・テストで用いる

In [ ]:
np.random.rand(10)    # 0~1の一様分布の乱数 0行１０列 生成

In [ ]:
a = np.random.rand(10, 10)    # 0~1の一様分布の乱数 10行１０列 生成
a

In [ ]:
a.shape

In [ ]:
# Standard Nomal Distribution(標準正規分布)
# mean(平均値)= 0 std(標準偏差)= 1 
np.random.randn(1)

In [ ]:
randn5000 = np.random.randn(5000, 5000)    # 5000行5000列

In [ ]:
randn5000.shape

In [ ]:
randn5000.mean()    # 限りなく０に近い平均値　※末尾に出たら、e-05＝１０のマイナス５乗

In [ ]:
randn5000.std()    # 限りなく１に近い標準偏差

In [ ]:
np.random.randint(1, 30, 30)    #1~30の乱数 0行30列 生成

In [ ]:
randint30 = np.random.randint(1, 30, (30, 30))    #1~30の乱数 30行30列 生成

In [ ]:
randint30.shape

In [ ]:
np.random.seed(100)
np.random.randn()    # seed固定 1回目

In [ ]:
np.random.randn()    # seed固定しない

In [ ]:
np.random.seed(100)
np.random.randn()    # seed固定　２回目（１回目同様のrandn生成）

## 行列の演算と処理
---

+ ```np.linalg.inv(ndarray)``` ndarrayの逆行列を算出
+ ```ndarray.T``` ndarrayの転置行列(Tranposed Matrix)を算出
+ ```np.diag(ndarray)``` ndarrayの対角成分の取得

### 内積　外積
+ ```np.inner()``` ベクトルの内積を算出
+ ```np.outer()``` ベクトルの外積を算出

Cf.[四元数と行列で見る内積と外積の「内」と「外」](https://qiita.com/7shi/items/a80988a32a0d706e9378)

In [ ]:
import numpy as np
a = np.array([[2, 5], [1, 3]])
a

In [ ]:
# a の逆行列　AA^-1 = A^-1A = I
b = np.linalg.inv(a)    # .linalg 線形代数(linear algebra) .inv 逆(inverse)
b

In [ ]:
# 単位行列　I　を求めて確認
np.dot(a, b)

In [ ]:
c = np.array([[3, 1], [2, 6], [4, 5]])
c

In [ ]:
c.shape

In [ ]:
c.T

In [ ]:
# 対角成分
d = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
d

In [ ]:
# 対角線上の「１」だけ取得
np.diag(d)    # .diag diagram

In [ ]:
# ベクトル
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
# ベクトル内積
np.inner(a, b)

In [ ]:
# ベクトル外戚
np.outer(a, b)

## 数学系の関数
---
### 三角関数
+ ```np.sin()``` sineを算出（度数ではなくラジアン）
+ ```np.cos()``` cosineを算出（度数ではなくラジアン）
+ ```np.tan()``` tangentを算出（度数ではなくラジアン）
+ ```np.radians()``` 度数からラジアンへ(弧度法)変換

![img](https://rikeilabo.com/wp-content/uploads/2018/11/三角比の表画像.png)

### 指数、対数関数
+ ```np.exp()``` 指数関数（Exponential / エクスポネンシャル）
+ ```np.log()``` 対数関数（Logarithm / ロガリズム）
+ ```np.sign()``` 「正」「負」「ゼロ」を分別
+ ```np.rint()``` 小数点を四捨五入して整数にする
+ ```np.modf()``` 小数点部と整数部に分けて配列で返す

In [ ]:
# tan 45° =1 
np.tan(45)    # 1 にはならない！ ∵度数ではなく、ラジアン指定の為

In [ ]:
# まず、度数からラジアンに変換
rd = np.radians(45)
rd

In [ ]:
np.tan(rd)    # ほぼ　１

In [ ]:
# sin 90° = 1
rd = np.radians(90)
np.sin(rd)

In [ ]:
# 指数関数　自然対数の底「e」
np.e

In [ ]:
np.exp(2)    # e^2

In [ ]:
a = np.array([1, 2, 3, 4, 5])
np.exp(a)    # Exponential(指数関数)

In [ ]:
np.log(a)    # Logarithm(対数関数）

In [ ]:
# 「-1」 「0」 「1」 で分別
b = np.array([-5, -1, -2, 0, 10, 5, -4, 3])
np.sign(b)

In [ ]:
c = np.random.randn(10)
c

In [ ]:
# 四捨五入
np.rint(c)

In [ ]:
# 小数点部と整数部に分けて配列で返す
np.modf(c)

In [ ]:
# exam
import numpy as np
a = np.array([[2, 5, 10], [3, 6, 8], [10, 23, 1]])
a[1, 2]

In [ ]:
import numpy as np
b = np.array([[2,7,10,2],[3,43,1,9]])
b[:,2]

In [ ]:
import numpy as np
b = np.array([[2,5],[6,1]])
a = np.array([[1,3],[2,4]])

a + b

In [ ]:
import numpy as np
a = np.array([[2,3],[6,2]])
b = np.array([[1,4],[5,2]])
a * b

In [ ]:
a = np.array([[2,3],[6,2]])
b = np.array([[1,4],[5,2]])
np.dot(a, b)

In [ ]:
a = np.array([[2,1],[1,2]])
b = np.linalg.inv(a)
np.dot(a, b)