# 線形代数 （Linear Algebra - リニアーアルジェブラ）

> 線型空間と線型変換を中心とした理論を研究する代数学の一分野。 もう少し噛み砕いた言い方だと、行列の性質や扱い方を考えた学問と捉えても問題ない。 link

```txt
基本的な線形代数は、機械学習を学ぶ際の必要最低限の知識。 機械学習では、PandasやNumpyで、データセット前処理として行列の演算などを行う。その際に「行列」の基本的な役割や扱い方の知識が必要。

また、線形代数をより深く理解することで、機械学習で使われるアルゴリズムをより深く理解できる。 アルゴリズムの理解が深まれば、より深いレベルでのアルゴリズムの実装や、さらには正しい理解のもとチューニングを行うことも可能。

線形代数を理解することで、機械学習で行えることや得られる結果に大きく幅を持つことが可能。
```


In [1]:
import numpy as np

a = np.array([[2,4],
              [0,4],
              [7,9],
              [3,7]])

b = np.array([[9,2],
              [4,1],
              [1,7],
              [0,2]])

print(a)

ModuleNotFoundError: No module named 'numpy'

In [4]:
# https://teratail.com/questions/122118
!which pip
!which pip3

/Users/t/.pyenv/versions/3.8.5/bin/pip
/Users/t/.pyenv/versions/3.8.5/bin/pip3


In [5]:
!pip install numpy

     |████████████████████████████████| 15.3 MB 802 kB/s eta 0:00:01


In [11]:
import numpy as np

a = np.array([[2,4],
              [0,4],
              [7,9],
              [3,7]])

b = np.array([[9,2],
              [4,1],
              [1,7],
              [0,2]])

In [12]:
print(a)

[[2 4]
 [0 4]
 [7 9]
 [3 7]]


In [13]:
print(a+b)

[[11  6]
 [ 4  5]
 [ 8 16]
 [ 3  9]]


In [14]:
a+b

array([[11,  6],
       [ 4,  5],
       [ 8, 16],
       [ 3,  9]])

In [15]:
np.dot(a, b)

ValueError: shapes (4,2) and (4,2) not aligned: 2 (dim 1) != 4 (dim 0)

## 行列とベクトル
---

+ 行列とは数字が超形状に並んだ配列
+ 行列は英語でマトリックス（Matrix / Matrices(複数形）)
+ 行列の縦部分を「行」（Row）
+ 行列の横部分を「列」（Column)
+ ```Xij``` i行j列の要素
+ ベクトルは「n x 1」または「1 x n」の行列

### 行列
```txt
M = [22, 123]
    [65, 54]
    [32, 1]

Mij
M１１(1行１列) = ２２
M22（2行２列） = 54
```

### ベクトル
```txt
v = [34]
    [2]
    [532]

v = [232 1 35 81]
```

#### ０オリジン、１オリジン（０インデックス、１インデックス）
```txt
Octave (機械学習で用いられる)：１インデックス
v = [v1 v2 v3 v4]

Python：０インデックス
v = [v0 v1 v2 v3]
```

In [12]:
# 行列　足し算
# (※同じ行列の形でないと計算不可)
import numpy as np
a = np.array([[2,4],
              [0,4],
              [7,9],
              [3,7]]) #4row2col
b = np.array([[9,2],
              [4,1],
              [1,7],
              [0,2]]) #4row2col
a + b

array([[11,  6],
       [ 4,  5],
       [ 8, 16],
       [ 3,  9]])

In [7]:
# 行列　スカラー倍
c = np.array([[1,3,7],
              [2,9,0]])

6 * c

array([[ 6, 18, 42],
       [12, 54,  0]])

In [8]:
# 行列　スカラー倍（割り算編）
d = np.array([[6,3],
              [0,1]])

d / 3 # = * 1/3　なのでスカラー倍

array([[2.        , 1.        ],
       [0.        , 0.33333333]])

In [11]:
# ベクトル計算
e = np.array([[2],[1],[0],[3]])
f = np.array([[4],[2],[3],[1]])
g = np.array([[6],[0],[3],[12]])

(5*e) - f + (g/6)

array([[ 7. ],
       [ 3. ],
       [-2.5],
       [16. ]])

In [15]:
# 行列　×　ベクトル　計算
import numpy as np
a = np.array([[2,5],[1,9],[0,3]]) # 行列　3行２列
b = np.array([[2],[3]]) # ベクトル　2行１列

np.dot(a, b) # 3行１列が出る

array([[19],
       [29],
       [ 9]])

In [17]:
# 練習
# 4行２列
c = np.array([[1,4],
              [2,0],
              [8,1],
              [3,5]])
# 2行１列
d = np.array([[1],
              [3]])

np.dot(c, d)

array([[13],
       [ 2],
       [11],
       [18]])

In [20]:
# 練習　（身長から体重を予測する）
# ４名の身長リスト :4行２列 行列
e = np.array([[1,180],
              [1,176],
              [1,156],
              [1,160]])
# 仮説（Hypothesis） :2行１列 ベクトル
f = np.array([[15],
              [0.32]])

np.dot(e, f)

array([[72.6 ],
       [71.32],
       [64.92],
       [66.2 ]])

In [21]:
# 行列 × 行列 計算
a = np.array([[1,3],
              [6,1],
              [2,0]]) # 3行２列
b = np.array([[0,2],
              [11,7]]) # 2行２列

np.dot(a, b)

array([[33, 23],
       [11, 19],
       [ 0,  4]])

In [22]:
c = np.array([[2,1,0],
              [9,6,2]]) # 2行３列
d = np.array([[8,0,2],
              [1,3,1],
              [7,4,0]]) # 3行３列

np.dot(c, d)

array([[17,  3,  5],
       [92, 26, 24]])

In [23]:
# 練習　（身長から体重を予測する）
# ４名の身長リスト :4行２列 行列
e = np.array([[1,180],
              [1,176],
              [1,156],
              [1,160]])
# 仮説（Hypothesis） :2行３列 ベクトル　# ３パターンの仮説
f = np.array([[  15,   8,  -7],
              [0.32,0.43,0.62]])

np.dot(e, f)

array([[ 72.6 ,  85.4 , 104.6 ],
       [ 71.32,  83.68, 102.12],
       [ 64.92,  75.08,  89.72],
       [ 66.2 ,  76.8 ,  92.2 ]])

### 行列の積の性質

+ 可換則（成り立たない）
> a×b != b×a
+ 結合法則（成り立つ）
> 4×2×3 = 4(2×3) =(4×3)3 = 24
>
> a×b×c
> d = b×c  e = a×b
> a×d = e×c
+ 単位行列「 I 」
> 1×B = B×1 = B
>
> (1)がBにおける単位行列

In [26]:
# 可換即
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [25]:
np.dot(b, a)

array([[23, 34],
       [31, 46]])

In [36]:
# 結合法則
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[2,1],[4,3]])

a.dot(b).dot(c)

array([[126,  85],
       [286, 193]])

In [33]:
e = np.dot(a, b)
e

array([[19, 22],
       [43, 50]])

In [34]:
d = np.dot(b, c)
d

array([[34, 23],
       [46, 31]])

In [35]:
print(e.dot(c))
print(a.dot(d))

[[126  85]
 [286 193]]
[[126  85]
 [286 193]]


In [47]:
# 単位行列
eye = np.eye(2) # 2行２列
eye

array([[1., 0.],
       [0., 1.]])

In [48]:
a

array([[1, 2],
       [3, 4]])

In [49]:
np.dot(eye, a)

array([[1., 2.],
       [3., 4.]])

In [50]:
np.dot(a, eye)

array([[1., 2.],
       [3., 4.]])

### 逆行列　転置行列

+ 単位元と逆数
> ３ × □ ＝ １
>
> ３に何かをかけて１となる状態＝単位元
>
> □　＝　逆数
>
> よって 1/3 (逆数は指数−１で表記する＝3^-1)
+ 逆行列
> m行m列の正方行列時しか成り立たない！
+ 転置行列
> m行n列の行列X、行列Xの転置行列X^T=Yとした時、
Yはn行m列の行列となる。


In [57]:
# A × A^-1 = I
a = np.array([[2,5],
              [1,3]]) # A
b = np.array([[3,-5],
              [-1,2]]) # 逆数： A^-1
np.dot(a, b) # 単位行列: I

array([[1, 0],
       [0, 1]])

In [58]:
# 逆行列の求め方
np.linalg.inv(a)

array([[ 3., -5.],
       [-1.,  2.]])

In [60]:
# 転置行列の求め方(Transposed)
c = np.array([[3,1],
              [2,6],
              [4,5]])
c.T

array([[3, 2, 4],
       [1, 6, 5]])

### アダマール積
> 同じ要素数を持った行列、或いは、ベクトルについて、同座標同士の掛け合わせを行う計算の仕方

cf. [numpyと、アダマール積](https://note.com/mucun_wuxian/n/n9c8e0ed3c8a6)

<img src='https://assets.st-note.com/production/uploads/images/27144341/rectangle_large_type_2_f1ad1e6620e6d56221d5944979e9b449.png' width=50%>


In [61]:
import numpy as np

A = np.array([[1, 4], 
              [3, 6], 
              [8, 2]])

B = np.array([[3, 2], 
              [5, 1], 
              [7, 10]])

print('A * B = ')
print(A * B)
print()
print('A.T @ B = ')
print(A.T @ B)

A * B = 
[[ 3  8]
 [15  6]
 [56 20]]

A.T @ B = 
[[74 85]
 [56 34]]
